model:
  model_name_or_path: "distilbert-base-uncased"
  max_length: 256

training:
  batch_size: 8
  num_epochs: 4
  learning_rate: 3e-5
  dataset_path: "./data/training_dataset.csv"
  validation_split: 0.2
  save_path: "./model_save/"

dataset:
  label_column: "label"
  text_column: "text"
